version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
      TYPE: VANILLA
      TZ: America/New_York
    volumes:
      - ./data:/data
